# Generated by Django 4.2.7 on 2023-11-05 11:55

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('uririconnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.localtime(timezone.now(), timezone=timezone.get_timezone('Africa/Nairobi'))),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roles',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
